Reformat DIYABC input file
===

> Code by Lotte van Boheemen



This conversion script requires as input a diyabc snp file. The goal of the current script is to 
- filter out loci with a set amount of missing data

Read data

```{r}
data<-read.table("filtered_passed_snps.DIYABC.snp", header=T)
```

```{r}
geno_cut <- 0.5 # SNP call rate
het_cut <- 0.7 # maximum heterozygosity

# create boolean values (TRUE/FALSE) for each column indicating if they passed the filter
het_pass <- apply(data, 2, function(x) length(which(x == "1"))/length(x)) <= het_cut
null_pass <- apply(data, 2, function(x) length(which(x == "9"))/length(x)) <= geno_cut
homref_pass <- apply(data,2, function(x) length(which(x == "0"))/length(x)) != 1
homalt_pass <- apply(data,2, function(x) length(which(x == "2"))/length(x)) != 1

#check if this worked by counting the number of loci which passed each filter
length(which(het_pass== "FALSE"))
length(which(het_pass== "TRUE"))
length(which(null_pass== "FALSE"))
length(which(null_pass== "TRUE"))
length(which(homref_pass== "FALSE"))
length(which(homalt_pass== "FALSE"))


# write columns passing the filter to new data frame
trydata <- data[het_pass]
trydata2 <- data[null_pass] #this works
sdata <- data[null_pass | het_pass] #but this doesn't

# Changing the order around of filtering
null_pass <- apply(trydata, 2, function(x) length(which(x == "9"))/length(x)) <= geno_cut
sdata <- data[null_pass]

# Maybe it's a good idea to sort on MAF before putting through diyABC. If I am going to subset before, MAF will be different. 

# write data drame to file
write.table(sdata,"diyabc_snp50_all")
```



---



Below also works to get the loci with less than the threshold of missing values. However, previous code is preferred as it is much faster.
```{r}
#set index for loops
i <- 1
j <- 1

# make a dataframe with only genotype information
ndata<-data[,-(1:3)]

#set up a 
result <- vector("list",100000000)
#test <- data.frame(index = numeric(), indexj = numeric(), count9 = numeric())

#make sure that the loop is not going past the maximum number of column                  
while(i <= ncol(ndata)){
  count9 <- length(which(ndata[,i] == 9)) 
  
  # create a vector to which to write to. Vectorisation works faster in R
  #vec <- numeric(10000000)
    
  if (count9 < geno_cut){
  #test[j,] <- c(i,j,count9) #this works, so the indexing is fine. Now need to write into   a vector
  #vec[j] <- ndata[,i]
  result[[j]] <- ndata[,i]
    
  j <- j + 1
  }
  
  i <-  i + 1
    
#output[[i]]  <- vec
}

df <- do.call("rbind",output) #that crashed the computer. Too much vm

```






