Spatial autocorrelation
===


Load in data and read STRUCTURE infiles
```{r, include=FALSE}
library(adegenet) #read.structure & basic stats
library(hierfstat) #pairwise Fst
library(ggplot2) #plotting
library(rgdal) #dependency of PopGenReport
library(PopGenReport) #other package for basic stats
library(pegas)
```

```{r}
allr<-read.structure("allcra473_240_in.stru", n.ind=473, n.loc=1000, onerowperind=FALSE, col.lab=1, col.pop=2, row.marknames=1,NA.char="-9", pop=85, ask=FALSE, quiet=FALSE)
all<-read.structure("all480_240_in.stru", n.ind=480, n.loc=1000, onerowperind=FALSE, col.lab=1, col.pop=2, row.marknames=1,NA.char="-9", pop=87, ask=FALSE, quiet=FALSE)
eu<-read.structure("eu199_240_in.stru", n.ind=199, n.loc=1000, onerowperind=FALSE, col.lab=1, col.pop=2, row.marknames=1, NA.char="-9", pop=36, ask=FALSE, quiet=FALSE)
nar<-read.structure("nacra232_240_in.stru", n.ind=232, n.loc=1000, onerowperind=FALSE, col.lab=1, col.pop=2, row.marknames=1,NA.char="-9", pop=42, ask=FALSE, quiet=FALSE)
au<-read.structure("au42_240_in.stru", n.ind=42, n.loc=1000, onerowperind=FALSE, col.lab=1, col.pop=2, row.marknames=1,NA.char="-9", pop=7,  ask=FALSE, quiet=FALSE)
```

Add data to genind object
```{r}
allother<-read.table("all476_other.txt",header=T)
all@other <- as.data.frame(allother[,1:6])
all@pop<-all@other[,1]
strata(all)<-data.frame(all@other[,3:4])
all@other$latlong<-data.frame(all@other[,5:6])

allrother<-read.table("allr470_other.txt",header=T)
allr@other <- as.data.frame(allrother[,1:6])
allr@pop<-allr@other[,1]
strata(allr)<-data.frame(allr@other[,3:4])
allr@other$latlong<-data.frame(allr@other[,5:6])

euother<-read.table("eu197_other.txt",header=T)
eu@other <- as.data.frame(euother[,1:6])
strata(eu)<-data.frame(eu@other[,3:4])
eu@pop<-eu@other[,1]
eu@other$latlong<-data.frame(eu@other[,5:6])

narother<-read.table("nar232_other.txt",header=T)
nar@other <- as.data.frame(narother[,1:6])
strata(nar)<-data.frame(nar@other[,3:4])
nar@pop<-nar@other[,1]
nar@other$latlong<-data.frame(nar@other[,5:6])

auother<-read.table("au41_other.txt",header=T)
au@other <- as.data.frame(auother[,1:6])
strata(au)<-data.frame(au$other[,3:4])
au@pop<-au@other[,1]
au@other$latlong<-data.frame(au@other[,5:6])
```
 
IBD using mantel

http://www2.uaem.mx/r-mirror/web/packages/adegenet/vignettes/adegenet-basics.pdf


```{r}
par(mfrow=c(3,1))
nar_gp <- genind2genpop(nar,process.other = TRUE)
Dgen_na <- dist.genpop(nar_gp,method=5) #provesti's distance, able to deal with missing data
Dgeo_na <- dist(nar_gp$other$latlong)
ibd_na <- mantel.randtest(Dgen_na,Dgeo_na,nrepet=5000)
#plot(ibd_na)
dens_na <- kde2d(Dgeo_na,Dgen_na, n=3000, lims=c(0, 40,-.5,4))
myPal <- colorRampPalette(c("white","blue","gold", "orange", "red"))
plot(Dgeo_na, Dgen_na, pch=20,cex=.5, xlab="Geographic distance",ylab="Genetic distance")
image(dens_na, col=transp(myPal(300),.5), add=TRUE)
abline(lm(Dgen_na~Dgeo_na))
text(30,0.215,labels="p < 0.001")
text(0,.215,labels="a.",col="black")
title("Isolation by distance native range")

eu_gp <- genind2genpop(eu,process.other = TRUE)
Dgen_eu <- dist.genpop(eu_gp,method=5) #provesti's distance, able to deal with missing data
Dgeo_eu <- dist(eu_gp$other$latlong)
ibd_eu <- mantel.randtest(Dgen_eu,Dgeo_eu,nrepet=5000)
#plot(ibd_eu)
abline
dens_eu <- kde2d(Dgeo_eu,Dgen_eu, n=3000, lims=c(0, 40,-.5,4))
plot(Dgeo_eu, Dgen_eu, pch=20,cex=.5, xlab="Geographic distance",ylab="Genetic distance")
image(dens_eu, col=transp(myPal(300),.5), add=TRUE)
text(25.5,0.22,labels="p = 0.146")
text(0,.22,labels="b.",col="black")
title("Isolation by distance invasive European range")

au_gp <- genind2genpop(au,process.other = TRUE)
Dgen_au <- dist.genpop(au_gp,method=5) #provesti's distance, able to deal with missing data
Dgeo_au <- dist(au_gp$other$latlong)
ibd_au <- mantel.randtest(Dgen_au,Dgeo_au,nrepet=5000)
#plot(ibd_au)
dens_au <- kde2d(Dgeo_au,Dgen_au, n=3000, lims=c(0, 40,-.5,4))
plot(Dgeo_au, Dgen_au, pch=20,cex=.5, xlab="Geographic distance",ylab="Genetic distance")
image(dens_au, col=transp(myPal(300),.5), add=TRUE)
text(8.5,0.165,labels="p = 0.157")
text(0.5,.213,labels="c.",col="black")
title("Isolation by distance invasive Australian range")
```





===
Using popgenreport (not working)

Spatial autocorr
```{r}



allr<-read.structure("allcra473_240_in.stru", n.ind=473, n.loc=1000, onerowperind=FALSE, col.lab=1, col.pop=2, row.marknames=1,NA.char="-9", pop=85, ask=FALSE, quiet=FALSE)
all<-read.structure("all480_240_in.stru", n.ind=480, n.loc=1000, onerowperind=FALSE, col.lab=1, col.pop=2, row.marknames=1,NA.char="-9", pop=87, ask=FALSE, quiet=FALSE)
all2000<-read.structure("all480_240_2000_2.stru", n.ind=480, n.loc=2000, onerowperind=FALSE, col.lab=1, col.pop=2, row.marknames=1,NA.char="-9", pop=87, ask=FALSE, quiet=FALSE)
eu<-read.structure("eu199_240_in.stru", n.ind=199, n.loc=1000, onerowperind=FALSE, col.lab=1, col.pop=2, row.marknames=1, NA.char="-9", pop=36, ask=FALSE, quiet=FALSE)
nar<-read.structure("nacra232_240_in.stru", n.ind=232, n.loc=1000, onerowperind=FALSE, col.lab=1, col.pop=2, row.marknames=1,NA.char="-9", pop=42, ask=FALSE, quiet=FALSE)
au<-read.structure("au42_240_in.stru", n.ind=42, n.loc=1000, onerowperind=FALSE, col.lab=1, col.pop=2, row.marknames=1,NA.char="-9", pop=7,  ask=FALSE, quiet=FALSE)
```

```{r}
allother<-read.table("all476_other.txt",header=T)
all@other <- as.data.frame(allother[,1:6])
all@pop<-all@other[,1]
strata(all)<-data.frame(all@other[,3:4])
all@other$latlong<-data.frame(all@other[,5:6])

allrother<-read.table("allr470_other.txt",header=T)
allr@other <- as.data.frame(allrother[,1:6])
allr@pop<-allr@other[,1]
strata(allr)<-data.frame(allr@other[,3:4])
allr@other$latlong<-data.frame(allr@other[,5:6])

euother<-read.table("eu197_other.txt",header=T)
eu@other <- as.data.frame(euother[,1:6])
strata(eu)<-data.frame(eu@other[,3:4])
eu@pop<-eu@other[,1]
eu@other$latlong<-data.frame(eu@other[,5:6])

narother<-read.table("nar232_other.txt",header=T)
nar@other <- as.data.frame(narother[,1:6])
strata(nar)<-data.frame(nar@other[,3:4])
nar@pop<-nar@other[,1]
nar@other$latlong<-data.frame(nar@other[,5:6])

auother<-read.table("au41_other.txt",header=T)
au@other <- as.data.frame(auother[,1:6])
strata(au)<-data.frame(au$other[,3:4])
au@pop<-au@other[,1]
au@other$latlong<-data.frame(au@other[,5:6])
```

```{r}
nar.out1<- popgenreport(nar_allsnp240,mk.counts=TRUE,mk.spautocor=TRUE, mk.pdf = TRUE,foldername = 'popgen_nar')
eu.out1<- popgenreport(eu_allsnp240,mk.counts=TRUE,mk.spautocor=TRUE,mk.pdf = TRUE,foldername = 'popgen_eu')
au.out1<- popgenreport(au_allsnp240,mk.counts=TRUE,mk.spautocor=TRUE, mk.pdf = TRUE,foldername = 'popgen_au')
```